### ISSUE TITLE
Error 400 when skill is called

### ISSUE THREAD

**Issue by Shugabuga** [patricksmith/pylexa#3]
I don't know if this is the right place to ask, but I am working on an Alexa skill that responds with the value of Bitcoin in USD, but every time I call it on the skill tester, I get the following error:

```
There was an error calling the remote endpoint, which returned HTTP 400 : BAD REQUEST
```

Trying on my local machine, I get this error:

```
[400] Cert chain URL not valid.
```

What could be the issue? The code is deployed on a Heroku server, if that helps. My code is below, if that helps (I used similar code in another skill and it worked):

```
import json
import os
import requests

from flask import Flask

from pylexa.app import alexa_blueprint
from pylexa.intent import handle_intent
from pylexa.app import handle_launch_request
from pylexa.response import PlainTextSpeech


app = Flask(__name__)
app.config['app_id'] = os.getenv('ALEXA_APP_ID')
app.register_blueprint(alexa_blueprint)

@handle_intent('GetBTC')
def handle_info_intent(request):
    try:
        print('Debug: ' + str(request.slots))
        btcValue = requests.get('http://api.coindesk.com/v2/bpi/currentprice.json').json()['bpi']['USD']['rate']
        print(btcValue)
        return PlainTextSpeech("Currently, Bitcoin is worth " + btcValue + " dollars.")
    except:
        return PlainTextSpeech("I don't know.")


@handle_intent('A')
@handle_launch_request
def handle_start_message(request):
    try:
        print("New launch!")
        btcValue = requests.get('http://api.coindesk.com/v2/bpi/currentprice.json').json()['bpi']['USD']['rate']
        print(btcValue)
        return PlainTextSpeech("Currently, Bitcoin is worth " + btcValue + " dollars.")
    except:
        return PlainTextSpeech("I don't know.")

if __name__ == '__main__':
    app.run(debug=True)
```

Intent schema:
```
{
  "intents": [
    {
      "slots": [
        {
          "name": "BTC",
          "type": "CURRENCY"
        }
      ],
      "intent": "GetBTC"
    }
  ]
}
```

Update: posted on [StackOverflow](https://stackoverflow.com/questions/45171799/error-400-when-alexa-skill-is-called) too.

**Comment by patricksmith** [comment]
Hi @Shugabuga. There could be a couple of things causing a "bad request" response. The app should automatically return the [error as part of the JSON response body](https://github.com/patricksmith/pylexa/blob/master/pylexa/app.py#L36) -- could you dump the response in a log file to see the error?

The 400 error usually occurs if the request did not pass verification ([everything that happens in this file](https://github.com/patricksmith/pylexa/blob/master/pylexa/verify.py)) or if the app id in the configuration (which I see is coming from `os.getenv('ALEXA_APP_ID')`) does not match the app id in the request.

To try it on your local machine, you can run the app with `app.config['debug'] = True` to skip all that verification and just test the business logic of your app.

**Comment by Shugabuga** [comment]
Sorry to bother you, but I found the issue. It was an issue with Amazon's debug tool. Solution was to test on an actual device.
<img width="820" alt="screen shot 2017-07-18 at 6 55 04 pm" src="https://user-images.githubusercontent.com/10801851/28343313-b938a164-6bea-11e7-92b3-16a55f77544c.png">
